# Generated by Django 4.1.2 on 2022-11-03 00:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d6c3855e-5409-4369-ab03-deee9fed24f1'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a2db9c2a-019f-46a9-addc-8f4fe09d9d6e'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stopping',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6706ba29-3721-4405-b94c-8d60176b5b45'), editable=False, primary_key=True, serialize=False)),
                ('has_agency', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stoppings', to='routes.city')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='cities',
            field=models.ManyToManyField(through='routes.Stopping', to='routes.route'),
        ),
    ]
