# Generated by Django 4.1.2 on 2022-11-20 21:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68010dbb-814a-4236-9f27-bc0b17c9811f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0e74dc7-8f93-4eac-b353-ec0a972958cf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stopping',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18c77e41-cac8-423a-9186-25727d22d2a5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
