# Generated by Django 4.1.2 on 2022-11-20 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_city_id_alter_route_id_alter_stopping_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('04d8c904-6395-4f59-ac94-34a73e017425'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3728acc3-bfcb-4859-aff5-1ee0fd8b8f7b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stopping',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2581d096-7bea-4647-bfc4-b8c834ce9bde'), editable=False, primary_key=True, serialize=False),
        ),
    ]
