# Generated by Django 4.1.2 on 2022-11-29 02:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_city_id_alter_route_id_alter_stopping_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e1f549e2-8190-449a-8afb-8b51d4866da8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5a8ea5a-2cf4-4fd0-b21f-78a7ce055852'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stopping',
            name='id',
            field=models.UUIDField(default=uuid.UUID('adf538ea-1b57-4ae4-bcf7-e71244f0b83d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
