# Generated by Django 4.1.2 on 2022-12-02 00:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_alter_city_id_alter_route_id_alter_stopping_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('df693449-a89d-41dc-8f46-7e625f6e051e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.UUIDField(default=uuid.UUID('85b190af-74de-426c-b640-f78110bde688'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stopping',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2bb0dc8b-e766-499f-9930-cf14097ae4d7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
