# Generated by Django 4.1.2 on 2022-12-02 00:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_alter_city_id_alter_route_id_alter_stopping_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('54c3eca9-2ad3-47cb-bbb5-76b0bf0932a8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.UUIDField(default=uuid.UUID('935d5e32-82f8-436c-9af7-7a22c1dd3b29'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stopping',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4370134b-789f-465a-bbcb-8bd668903198'), editable=False, primary_key=True, serialize=False),
        ),
    ]
