# Generated by Django 4.1.2 on 2022-12-02 00:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_alter_city_id_alter_route_id_alter_stopping_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7deba8a5-e80c-4d3e-8888-97a3bea10727'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e24e4cac-e6e7-48be-ba5d-adefb5450263'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stopping',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4cee457d-60b3-4be1-8e4b-8f45bec1eadb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
