# Generated by Django 4.1.2 on 2022-12-02 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_alter_city_id_alter_route_id_alter_stopping_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed39eb83-245c-451f-a2f6-86bb1201e7e1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.UUIDField(default=uuid.UUID('07074066-cbaf-40cf-832c-e1a01b6e8fff'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stopping',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b1418d0f-e33a-4861-94c5-852fd5481b59'), editable=False, primary_key=True, serialize=False),
        ),
    ]
