# Generated by Django 4.1.2 on 2022-12-05 22:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_alter_city_id_alter_route_id_alter_stopping_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.UUID('664a5990-afbb-47d3-9348-caf529e76011'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b20380e2-9030-4821-ad06-2157ce109686'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stopping',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5762dbde-f7fc-4e4c-a140-6910d3217821'), editable=False, primary_key=True, serialize=False),
        ),
    ]
