# Generated by Django 4.1.2 on 2022-11-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
