# Generated by Django 4.1.2 on 2022-12-05 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0014_alter_city_id_alter_route_id_alter_stopping_id'),
        ('vehicles', '0003_vehicle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.route'),
        ),
    ]
